name: Schema Processing Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  process_schema:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        cd scripts
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python scripts/generate_current_schema_documentation.py --source-dir $GITHUB_WORKSPACE

    - name: Commit and push changes
      run: |
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config user.name "${GITHUB_ACTOR}"
        git add docs/  
        git commit -am "Regenerated docs based on schema updates"
        git push origin HEAD:${{ github.event.pull_request.base.ref }}
