name: Schema Processing Pipeline

on:
  push:
    branches: [ mkdocs ]

jobs:


  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Print GITHUB_WORKSPACE
        run: echo "The value of GITHUB_WORKSPACE is $GITHUB_WORKSPACE"

      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: |
          cd $GITHUB_WORKSPACE/docs
          mkdocs gh-deploy