name: Schema Processing Pipeline

on:
  push:
    branches: [ mkdocs ]

jobs:
  process_schema:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        cd scripts
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python scripts/generate_current_schema_documentation.py --source-dir $GITHUB_WORKSPACE

    - name: Commit and push changes
      run: |
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config user.name "${GITHUB_ACTOR}"
        git add docs/  
        git commit -am "Regenerated docs based on schema updates"
        git push origin HEAD:refs/heads/mkdocs


  build-and-deploy:
    needs: process_schema

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy